name: Deploiement

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run unit tests
        run: python -m pytest
        
      - name: Configure Heroku CLI
        run: |
          echo machine api.heroku.com > %USERPROFILE%\.netrc
          echo   login johan.rocheteau@hotmail.fr >> %USERPROFILE%\.netrc
          echo   password $HEROKU_API_KEY >> %USERPROFILE%\.netrc
          echo machine git.heroku.com >> %USERPROFILE%\.netrc
          echo   login johan.rocheteau@hotmail.fr >> %USERPROFILE%\.netrc
          echo   password $HEROKU_API_KEY >> %USERPROFILE%\.netrc
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      
      - name: Deploy to Heroku
        run: heroku container:push web -a prediction-app-p7
      
      - name: Deploy to Heroku
        run: heroku container:push web -a prediction-app-p7
